"""share

Revision ID: 96b147d19892
Revises: d38dc4da3d79
Create Date: 2025-01-04 12:21:04.381836

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96b147d19892"
down_revision: Union[str, None] = "d38dc4da3d79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_public as nullable first
    op.add_column("chats", sa.Column("is_public", sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE chats SET is_public = false WHERE is_public IS NULL")
    # Make it not nullable
    op.alter_column("chats", "is_public", existing_type=sa.Boolean(), nullable=False)

    op.add_column("chats", sa.Column("public_share_id", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_chats_public_share_id"), "chats", ["public_share_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chats_public_share_id"), table_name="chats")
    op.drop_column("chats", "public_share_id")
    op.drop_column("chats", "is_public")
    # ### end Alembic commands ###
