"""add pack_hash to prepared_sandboxes

Revision ID: d76f873e45f9
Revises: 
Create Date: 2024-12-03 18:22:12.277067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd76f873e45f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prepared_sandboxes', sa.Column('pack_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prepared_sandboxes', 'pack_hash')
    # ### end Alembic commands ###
